// The built-in functions a formula can pass as a value, the way `SUM` is passed in `BYROW(A1:A3,SUM)`,
// keyed by uppercased name. Excel stores such a name under `_xleta.`, as `_xlfn.BYROW(A1:A3,_xleta.SUM)`;
// the same name stored bare is a reference to a defined name called `SUM`, which Excel shows as `#NAME?`
// when the workbook defines none. `formula.ts` is the single place that applies and removes the prefix.
//
// No specification lists these, so the list is Excel's own answer. Excel Desktop 16.0 (build 20326) was
// given `=MAP(1,<name>)` for every name in the [MS-XLS] function table, the future-function registry,
// the Analysis ToolPak and the members of its own `WorksheetFunction` object, and saved the workbook;
// the names it wrote with the prefix are the ones here. What it left bare is as telling: the XLM macro
// functions of the function table (`GOTO`, `GET.CELL`), `TRUE`, `FALSE` and `LOG10`, which read as
// literals and a cell, and the four post-2007 names it also calls without a prefix (`NETWORKDAYS.INTL`,
// `WORKDAY.INTL`, `ISO.CEILING`, `ECMA.CEILING`).
//
// Every future function is a value but the six in `NOT_VALUES`, so what is written out below is only
// the functions older than that registry, and a name added to it is a value from the day it is added.

import {FUTURE_FUNCTION_PREFIXES} from './future-functions.ts';

// Grouped by initial letter so a diff against a later observation reads line by line.
const OLDER_FUNCTIONS = `
  ABS ACCRINT ACCRINTM ACOS ACOSH ADDRESS AMORDEGRC AMORLINC AND AREAS ASC ASIN ASINH ATAN ATAN2 ATANH
  AVEDEV AVERAGE AVERAGEA AVERAGEIF AVERAGEIFS
  BAHTTEXT BESSELI BESSELJ BESSELK BESSELY BETADIST BETAINV BIN2DEC BIN2HEX BIN2OCT BINOMDIST
  CEILING CELL CHAR CHIDIST CHIINV CHITEST CHOOSE CLEAN CODE COLUMN COLUMNS COMBIN COMPLEX CONCATENATE
  CONFIDENCE CONVERT CORREL COS COSH COUNT COUNTA COUNTBLANK COUNTIF COUNTIFS COUPDAYBS COUPDAYS
  COUPDAYSNC COUPNCD COUPNUM COUPPCD COVAR CRITBINOM CUBEKPIMEMBER CUBEMEMBER CUBEMEMBERPROPERTY
  CUBERANKEDMEMBER CUBESET CUBESETCOUNT CUBEVALUE CUMIPMT CUMPRINC
  DATE DATEDIF DATESTRING DATEVALUE DAVERAGE DAY DAYS360 DB DBCS DCOUNT DCOUNTA DDB DEC2BIN DEC2HEX
  DEC2OCT DEGREES DELTA DEVSQ DGET DISC DMAX DMIN DOLLAR DOLLARDE DOLLARFR DPRODUCT DSTDEV DSTDEVP DSUM
  DURATION DVAR DVARP
  EDATE EFFECT EOMONTH ERF ERFC ERROR.TYPE EVEN EXACT EXP EXPONDIST
  FACT FACTDOUBLE FDIST FIND FINDB FINV FISHER FISHERINV FIXED FLOOR FORECAST FREQUENCY FTEST FV
  FVSCHEDULE
  GAMMADIST GAMMAINV GAMMALN GCD GEOMEAN GESTEP GETPIVOTDATA GROWTH
  HARMEAN HEX2BIN HEX2DEC HEX2OCT HLOOKUP HOUR HYPERLINK HYPGEOMDIST
  IF IFERROR IMABS IMAGINARY IMARGUMENT IMCONJUGATE IMCOS IMDIV IMEXP IMLN IMLOG10 IMLOG2 IMPOWER
  IMPRODUCT IMREAL IMSIN IMSQRT IMSUB IMSUM INDEX INDIRECT INFO INT INTERCEPT INTRATE IPMT IRR ISBLANK
  ISERR ISERROR ISEVEN ISLOGICAL ISNA ISNONTEXT ISNUMBER ISODD ISPMT ISREF ISTEXT ISTHAIDIGIT
  KURT
  LARGE LCM LEFT LEFTB LEN LENB LINEST LN LOG LOGEST LOGINV LOGNORMDIST LOOKUP LOWER
  MATCH MAX MAXA MDETERM MDURATION MEDIAN MID MIDB MIN MINA MINUTE MINVERSE MIRR MMULT MOD MODE MONTH
  MROUND MULTINOMIAL
  N NA NEGBINOMDIST NETWORKDAYS NOMINAL NORMDIST NORMINV NORMSDIST NORMSINV NOT NOW NPER NPV
  NUMBERSTRING
  OCT2BIN OCT2DEC OCT2HEX ODD ODDFPRICE ODDFYIELD ODDLPRICE ODDLYIELD OFFSET OR
  PEARSON PERCENTILE PERCENTRANK PERMUT PHONETIC PI PMT POISSON POWER PPMT PRICE PRICEDISC PRICEMAT
  PROB PRODUCT PROPER PV
  QUARTILE QUOTIENT
  RADIANS RAND RANDBETWEEN RANK RATE RECEIVED REPLACE REPLACEB REPT RIGHT RIGHTB ROMAN ROUND
  ROUNDBAHTDOWN ROUNDBAHTUP ROUNDDOWN ROUNDUP ROW ROWS RSQ RTD
  SEARCH SEARCHB SECOND SERIES SERIESSUM SIGN SIN SINH SKEW SLN SLOPE SMALL SQRT SQRTPI STANDARDIZE
  STDEV STDEVA STDEVP STDEVPA STEYX SUBSTITUTE SUBTOTAL SUM SUMIF SUMIFS SUMPRODUCT SUMSQ SUMX2MY2
  SUMX2PY2 SUMXMY2 SYD
  T TAN TANH TBILLEQ TBILLPRICE TBILLYIELD TDIST TEXT THAIDAYOFWEEK THAIDIGIT THAIMONTHOFYEAR
  THAINUMSOUND THAINUMSTRING THAISTRINGLENGTH THAIYEAR TIME TIMEVALUE TINV TODAY TRANSPOSE TREND TRIM
  TRIMMEAN TRUNC TTEST TYPE
  UPPER USDOLLAR
  VALUE VAR VARA VARP VARPA VDB VLOOKUP
  WEEKDAY WEEKNUM WEIBULL WORKDAY
  XIRR XNPV
  YEAR YEARFRAC YIELD YIELDDISC YIELDMAT
  ZTEST
`;

// The future functions Excel left bare. LAMBDA and LET bind names rather than compute a value, and the
// other four are Python and Power Query plumbing.
export const NOT_VALUES: ReadonlySet<string> = new Set([
  'LAMBDA',
  'LET',
  'PYTHON_STR',
  'PYTHON_TYPE',
  'PYTHON_TYPENAME',
  'QUERYSTRING',
]);

export const OLDER_FUNCTION_VALUES: readonly string[] = OLDER_FUNCTIONS.trim().split(/\s+/);

/** Every built-in function Excel stores under `_xleta.` when a formula passes it as a value. */
export const FUNCTION_VALUE_NAMES: ReadonlySet<string> = new Set([
  ...OLDER_FUNCTION_VALUES,
  ...[...FUTURE_FUNCTION_PREFIXES.keys()].filter((name) => !NOT_VALUES.has(name)),
]);
