// The functions Excel stores under a future-function prefix, keyed by uppercased name, with the prefix
// each one takes on disk. OOXML froze its function grammar around Excel 2007; a function added since is
// unknown to an older reader under its bare name, so the writer stores it prefixed and the reader strips
// the prefix back. `formula.ts` is the single place that applies and removes it, and it treats '.' as
// part of a function name, so a dotted name such as NORM.DIST is matched and prefixed whole.
//
// The source is [MS-XLSX] revision 29.1 (May 2026): the future-function-list and
// worksheet-only-function-list rules of its Formulas grammar (section 2.2.2), repeated in its table of
// future functions. That table also names NETWORKDAYS.INTL, WORKDAY.INTL, ISO.CEILING and ECMA.CEILING
// with no prefix, and Excel Desktop 16.0 (build 20326) writes them bare, so they are absent here. The
// same Excel wrote every name in the last list with `_xlfn.` although the specification does not list
// it yet. A name missing from this registry is written bare, which current Excel reads as `#NAME?`.

/** The prefix a future function carries on disk. */
export type FutureFunctionPrefix = '_xlfn.' | '_xlfn._xlws.';

// The specification's worksheet-only functions, which take `_xlws.` after `_xlfn.`.
const WORKSHEET_ONLY_FUNCTIONS = ['FILTER', 'PY', 'SORT'];

// The specification's future functions, alphabetical as it tabulates them.
const SPECIFIED_FUNCTIONS = [
  'ACOT',
  'ACOTH',
  'AGGREGATE',
  'ARABIC',
  'BASE',
  'BETA.DIST',
  'BETA.INV',
  'BINOM.DIST',
  'BINOM.DIST.RANGE',
  'BINOM.INV',
  'BITAND',
  'BITLSHIFT',
  'BITOR',
  'BITRSHIFT',
  'BITXOR',
  'BYCOL',
  'BYROW',
  'CEILING.MATH',
  'CEILING.PRECISE',
  'CHISQ.DIST',
  'CHISQ.DIST.RT',
  'CHISQ.INV',
  'CHISQ.INV.RT',
  'CHISQ.TEST',
  'CHOOSECOLS',
  'CHOOSEROWS',
  'COMBINA',
  'CONCAT',
  'CONFIDENCE.NORM',
  'CONFIDENCE.T',
  'COT',
  'COTH',
  'COVARIANCE.P',
  'COVARIANCE.S',
  'CSC',
  'CSCH',
  'DAYS',
  'DECIMAL',
  'DROP',
  'ERF.PRECISE',
  'ERFC.PRECISE',
  'EXPAND',
  'EXPON.DIST',
  'F.DIST',
  'F.DIST.RT',
  'F.INV',
  'F.INV.RT',
  'F.TEST',
  'FIELDVALUE',
  'FILTERXML',
  'FLOOR.MATH',
  'FLOOR.PRECISE',
  'FORECAST.ETS',
  'FORECAST.ETS.CONFINT',
  'FORECAST.ETS.SEASONALITY',
  'FORECAST.ETS.STAT',
  'FORECAST.LINEAR',
  'FORMULATEXT',
  'GAMMA',
  'GAMMA.DIST',
  'GAMMA.INV',
  'GAMMALN.PRECISE',
  'GAUSS',
  'HSTACK',
  'HYPGEOM.DIST',
  'IFNA',
  'IFS',
  'IMCOSH',
  'IMCOT',
  'IMCSC',
  'IMCSCH',
  'IMSEC',
  'IMSECH',
  'IMSINH',
  'IMTAN',
  'ISFORMULA',
  'ISOMITTED',
  'ISOWEEKNUM',
  'LAMBDA',
  'LET',
  'LOGNORM.DIST',
  'LOGNORM.INV',
  'MAKEARRAY',
  'MAP',
  'MAXIFS',
  'MINIFS',
  'MODE.MULT',
  'MODE.SNGL',
  'MUNIT',
  'NEGBINOM.DIST',
  'NORM.DIST',
  'NORM.INV',
  'NORM.S.DIST',
  'NORM.S.INV',
  'NUMBERVALUE',
  'PDURATION',
  'PERCENTILE.EXC',
  'PERCENTILE.INC',
  'PERCENTRANK.EXC',
  'PERCENTRANK.INC',
  'PERMUTATIONA',
  'PHI',
  'POISSON.DIST',
  'PQSOURCE',
  'PYTHON_STR',
  'PYTHON_TYPE',
  'PYTHON_TYPENAME',
  'QUARTILE.EXC',
  'QUARTILE.INC',
  'QUERYSTRING',
  'RANDARRAY',
  'RANK.AVG',
  'RANK.EQ',
  'REDUCE',
  'RRI',
  'SCAN',
  'SEC',
  'SECH',
  'SEQUENCE',
  'SHEET',
  'SHEETS',
  'SKEW.P',
  'SORTBY',
  'STDEV.P',
  'STDEV.S',
  'SWITCH',
  'T.DIST',
  'T.DIST.2T',
  'T.DIST.RT',
  'T.INV',
  'T.INV.2T',
  'T.TEST',
  'TAKE',
  'TEXTAFTER',
  'TEXTBEFORE',
  'TEXTJOIN',
  'TEXTSPLIT',
  'TOCOL',
  'TOROW',
  'UNICHAR',
  'UNICODE',
  'UNIQUE',
  'VAR.P',
  'VAR.S',
  'VSTACK',
  'WEBSERVICE',
  'WEIBULL.DIST',
  'WRAPCOLS',
  'WRAPROWS',
  'XLOOKUP',
  'XOR',
  'Z.TEST',
];

// Written with `_xlfn.` by Excel Desktop 16.0 (build 20326) and not yet in the specification. SINGLE is
// how Excel stores an `@` inside a dynamic-array formula, and ANCHORARRAY how it stores a spill
// reference such as `E1#`; both reach the model through a read and must be prefixed again on write.
const OBSERVED_FUNCTIONS = [
  'ANCHORARRAY',
  'ARRAYTOTEXT',
  'DETECTLANGUAGE',
  'ENCODEURL',
  'GROUPBY',
  'IMAGE',
  'PERCENTOF',
  'PIVOTBY',
  'REGEXEXTRACT',
  'REGEXREPLACE',
  'REGEXTEST',
  'SINGLE',
  'STOCKHISTORY',
  'TRANSLATE',
  'TRIMRANGE',
  'VALUETOTEXT',
  'XMATCH',
];

export const FUTURE_FUNCTION_PREFIXES: ReadonlyMap<string, FutureFunctionPrefix> = new Map([
  ...WORKSHEET_ONLY_FUNCTIONS.map((name) => [name, '_xlfn._xlws.'] as const),
  ...SPECIFIED_FUNCTIONS.map((name) => [name, '_xlfn.'] as const),
  ...OBSERVED_FUNCTIONS.map((name) => [name, '_xlfn.'] as const),
]);
